name: Working Directory Parity Test
on: push
jobs:
  test-working-directory:
    runs-on: local
    steps:
      - name: Prepare relative directory
        run: mkdir -p relative-dir

      - name: Absolute working directory
        run: |
          expected_tmp="$(cd /tmp && pwd -P)"
          if [ "$(pwd -P)" != "$expected_tmp" ]; then
            echo "expected $expected_tmp, got $(pwd -P)"
            exit 1
          fi
          echo "absolute working-directory ok"
        working-directory: /tmp

      - name: Relative working directory
        run: |
          expected_workspace_relative="$(cd "$GITHUB_WORKSPACE/relative-dir" && pwd -P)"
          if [ "$(pwd -P)" != "$expected_workspace_relative" ]; then
            echo "expected $expected_workspace_relative, got $(pwd -P)"
            exit 1
          fi
          echo "relative working-directory ok"
        working-directory: relative-dir
