on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print-env
        run: |
          echo $MY_SPECIAL_ENV_VAR
      - name: store to env
        run: |
          set -euo pipefail
          echo "inline_env_var=$MY_SPECIAL_ENV_VAR" >> $GITHUB_ENV
      - name: print from inline env var
        run: echo value is $inline_env_var

      - name: path set
        run: |
          set -euo pipefail
          mkdir -p bin
          cat <<'EOF' > bin/custom_executable
          #!/usr/bin/env bash
          echo "hello from $(basename $0)"
          pwd
          EOF

          chmod +x bin/custom_executable
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: path check
        run: |
          echo $PATH
          type custom_executable
          custom_executable
          rm -rf ./bin
