// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package runner

import (
	"errors"
	"fmt"
)

const (
	// WorkflowCommandNameDebug is a WorkflowCommandName of type debug.
	WorkflowCommandNameDebug WorkflowCommandName = "debug"
)

var ErrInvalidWorkflowCommandName = errors.New("not a valid WorkflowCommandName")

// String implements the Stringer interface.
func (x WorkflowCommandName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WorkflowCommandName) IsValid() bool {
	_, err := ParseWorkflowCommandName(string(x))
	return err == nil
}

var _WorkflowCommandNameValue = map[string]WorkflowCommandName{
	"debug": WorkflowCommandNameDebug,
}

// ParseWorkflowCommandName attempts to convert a string to a WorkflowCommandName.
func ParseWorkflowCommandName(name string) (WorkflowCommandName, error) {
	if x, ok := _WorkflowCommandNameValue[name]; ok {
		return x, nil
	}
	return WorkflowCommandName(""), fmt.Errorf("%s is %w", name, ErrInvalidWorkflowCommandName)
}
